### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by claynaut** [citrushack/cutiehack2021#12]
**Task:** Handle making/joining groups or teams.

- Hackers have the option to create or join a group (must be signed in first).
- Creating a group: a group is generated with a unique ID.
  - Other hackers can use this ID to join.
- Joining a group: hackers input a unique ID to join a group.
  - If the group exists, the hacker becomes part of the group.
  - Otherwise, display an error message.
- Frontend needed to make the UI for group making.
- Backend need to handle API-related tasks and writing groups to the DB.

**Comment by rajbirjohar** [comment]
Recommend [Nanoid](https://www.npmjs.com/package/nanoid)
