### ISSUE TITLE
Hide some nav links on any page other than the homepage

### ISSUE THREAD

**Issue by claynaut** [citrushack/cutiehack2021#22]
**Task:** Make it so that only the full navbar (links to about, FAQ, sponsors, etc.) are only visible on the homepage ("/").

- On any page other than the homepage, only a nav link to home and additional buttons (check in, sign in/out) should be visible.

**Comment by rajbirjohar** [comment]
I have another suggestion/fix to this using the [ActiveLink Component](https://github.com/rajbirjohar/Portfolio/blob/master/components/ActiveLink.js).

This way, you can apply a style to the link on whichever page is active such as an underline or a text color change. What do you think?
